### ISSUE TITLE
layout: Font

### ISSUE THREAD

**Issue by mcnLeandro** [Recursion-Group-K/sketch#18]
サイトのフォントがデフォルトよりかは変えたほうがいいと思います！

皆さんお気に入りのフォントはありますか？？

**Comment by sokahiri** [comment]
フォントについて全然詳しくないのでこれがいいとかは言えませんが、確かにフォントは共通のものを使った方がよさそうですね！

**Comment by mcnLeandro** [comment]
ですね！
こちらの中から決めても良さようです＠
https://xd.adobe.com/ideas/principles/web-design/best-modern-fonts-for-websites/

**Comment by Jin2oo2** [comment]
僕は6番のMerriweather Italicがおしゃれで見やすいので個人的に好きです！

**Comment by sokahiri** [comment]
見てみましたが自分は4番が一番好みでした！

**Comment by mcnLeandro** [comment]
皆さんありがとうございます！
他のページも出来上がってくると思うので、フォントはもうちょっと時間をかけて決めていきますね！
一応あげていただいたものを使ったログインページの写真を撮っておきました。
タイトルの部分はそのまま使ってます。

## Merriweather
### Regular Italic
<img width="1045" alt="sshot" src="https://user-images.githubusercontent.com/72016706/150169985-cade4049-f2f2-4d61-a919-1b237fbfdc65.png">

```css
@import url('https://fonts.googleapis.com/css2?family=Merriweather:ital@1&display=swap');
#app {
  font-family: 'Merriweather', sans-serif;
}
```

## Open sans
### Regular
<img width="994" alt="sshot" src="https://user-images.githubusercontent.com/72016706/150171051-21a4ccd3-c7cc-46d2-9048-9a3b23f7d7bc.png">

```css
@import url('https://fonts.googleapis.com/css2?family=Open+Sans&display=swap');
#app {
    font-family: 'Open Sans', sans-serif;
}
```

## Playfair Display
### Regular
<img width="967" alt="sshot" src="https://user-images.githubusercontent.com/72016706/150171858-8c4f6b19-e6d2-4ffd-8cfa-7d574ba9b71a.png">

```css
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap');
#app {
    font-family: 'Playfair Display', serif;
}
````
